version: "3.8"

services:
  bot:
    build: ./bot
    container_name: discord-bot
    env_file: .env
    restart: always
    depends_on:
      - server

  server:
    build: ./server
    container_name: api-server
    ports:
      - "3001:3001"
    restart: always
    environment:
      - PORT=3001

  dashboard:
    build: ./dashboard
    container_name: bot-dashboard
    ports:
      - "5173:80"
    restart: always
    depends_on:
      - server
